# run on container environment
sudo: false

language: php

php: 7.1
    
script:
    - phpenv config-rm xdebug.ini || return 0
    - cd ../../
    - composer require apigen/apigen
    - dir
    - mkdir repo_docs
    - ./vendor/bin/apigen generate -s ./vsp-libs/apigen-boilerplate --destination ./docs
    - cd docs
    - dir
