# run on container environment
sudo: false

language: php

php: 7.1
    
script:
    - phpenv config-rm xdebug.ini || return 0
    - cd ../../
    - composer require apigen/apigen
    - dir
    - mkdir repo_docs
    - cd repo_docs
    - git clone https://github.com/johnbillion/extended-cpts.git
    - git checkout -f gh-pages
    - dir
    - ls -l
    - ./vendor/bin/apigen generate -s ./vsp-libs/apigen-boilerplate --destination ./docs
    - cd docs
    - dir
    - ls -l
