# run on container environment
sudo: false

language: php

php: 7.1
    
script:
    - phpenv config-rm xdebug.ini || return 0
    - cd ../../
    - composer require apigen/apigen
    - bash vsp-libs/apigen-boilerplate/build.sh
