language: php

sudo: false

php: 7.1


install:
    # install composer dependencies
    - composer require apigen/apigen --dev
    # Create composer global installs
    - composer create-project apigen/apigen:dev-master temp/apigen-project
    # - composer global require apigen/apigen:dev-master

script:
    # Turn off XDebug to make the rest faster
    - phpenv config-rm xdebug.ini || return 0

    # Global install checks
    - temp/apigen-project/bin/apigen generate -h
    # disable for now, due to commit lock on opened PR
    # https://github.com/ApiGen/ApiGen/commit/891bdf8c8090ee72028943bb9d06d1accda27daf
    # https://github.com/Roave/BetterReflection/pull/312
    # - ~/.composer/vendor/bin/apigen generate -h

after_script:
   
    # Generate ApiGen's api a push it to https://github.com/apigen/apigen, gh-pages branch
    - |
        if [[ $TRAVIS_BRANCH == "master" ]]; then
          dir
          # Generate API for ApiGen
          bin/apigen generate ../../vsp-libs/apigen-boilerplate --destination temp/api
          # use this, when ApiGen is faster
          # bin/apigen generate src packages/*/src --destination temp/api
          cd temp/api

          # Add this repository as remote
          git init
          git remote add origin https://${GH_TOKEN}@github.com/vsp-libs/apigen-boilerplate.git

          # Set Travis to Git Identity
          git config --global user.email "travis@travis-ci.org"
          git config --global user.name "Travis"

          # Add generated API
          git add .
          git commit -m "API Regenerated"

          # Push current content to gh-pages branch
          git push origin master:gh-pages -f
        fi

# do not send emails
notifications:
    email: never
