# run on container environment
sudo: false

language: php

php: 7.1
    
script:
    - phpenv config-rm xdebug.ini || return 0
    - cd ../../
    - dir
    - mkdir repo_docs
    - git clone --branch=gh-pages https://github.com/vsp-libs/apigen-boilerplate.git ./repo_docs
    - composer require apigen/apigen
    - ./vendor/bin/apigen generate -s ./vsp-libs/apigen-boilerplate --destination ./repo_docs
    - cd repo_docs
    - ls -l
